#include <Windows.h>
#include <string.h>

#include "cardmod.h"
#include "logging.h"
#include "minidriver.h"
#include "pkcs11.h"

// clang-format off
// This is the list of functions required by the spec
// that we **do not want** to support.
// Please make sure any function is either listed here
// or has a concrete definition. Otherwise, this mini driver
// would be silently ignored by CSP.
#define INVOKE_X_ON_NO_IMPL_FUNCS(X) \
X(CardDeleteContainer) \
X(CardGetChallenge) \
X(CardAuthenticateChallenge) \
X(CardCreateDirectory) \
X(CardDeleteDirectory) \
X(CardDeleteFile) \
X(CardSetContainerProperty) \
X(CardGetChallengeEx) \
X(MDImportSessionKey) \
X(MDEncryptData) \
X(CardImportSessionKey) \
X(CardGetSharedKeyHandle) \
X(CardGetAlgorithmProperty) \
X(CardGetKeyProperty) \
X(CardSetKeyProperty) \
X(CardDestroyKey) \
X(CardProcessEncryptedData)

#define CMD_NO_IMPL_FUNC_NAME(NAME) __cmd_noimpl__ ## NAME
#define CMD_GEN_NO_IMPL_FUNC(NAME) DWORD WINAPI CMD_NO_IMPL_FUNC_NAME(NAME)(__inout PCARD_DATA pCardData, ...) { \
CMD_ERROR(#NAME " is not meant to be supported but called with pCardData %p", pCardData); \
CMD_RETURN(SCARD_E_UNSUPPORTED_FEATURE, "not meant to be supported (generated by macro)"); \
}
INVOKE_X_ON_NO_IMPL_FUNCS(CMD_GEN_NO_IMPL_FUNC);
#undef CMD_GEN_NO_IMPL_FUNC
// clang-format on

// Global function pointers for memory management
PFN_CSP_ALLOC g_pfnCspAlloc = NULL;
PFN_CSP_FREE g_pfnCspFree = NULL;

// Global function pointer for padding
PFN_CSP_PAD_DATA g_pfnCspPadData = NULL;
SRWLOCK g_cmd_context_lock = SRWLOCK_INIT;

static void release_exclusive_context_lock(PSRWLOCK *lock) {
  if (lock != NULL && *lock != NULL)
    ReleaseSRWLockExclusive(*lock);
}

static CK_RV cleanup_failed_acquire(CK_SESSION_HANDLE session, BOOL sessionOpen) {
  CK_RV result = CKR_OK;
  if (sessionOpen) {
    CK_RV closeRv = C_CloseSession(session);
    if (closeRv != CKR_OK && closeRv != CKR_SESSION_HANDLE_INVALID && closeRv != CKR_CRYPTOKI_NOT_INITIALIZED) {
      CMD_WARN("C_CloseSession during acquire cleanup failed: 0x%lx", closeRv);
      result = closeRv;
    }
  }
  CK_RV finalizeRv = C_Finalize(NULL);
  if (finalizeRv != CKR_OK && finalizeRv != CKR_CRYPTOKI_NOT_INITIALIZED) {
    CMD_WARN("C_Finalize during acquire cleanup failed: 0x%lx", finalizeRv);
    if (result == CKR_OK)
      result = finalizeRv;
  }
  return result;
}

/*
 * Function: CardAcquireContext
 *
 * Purpose: Initialize the CARD_DATA structure which will be used by
 *          the CSP to interact with a specific card.
 */
DWORD WINAPI CardAcquireContext(__inout PCARD_DATA pCardData, __in DWORD dwFlags) {
  CMD_LOG_FUNC("pCardData %p, dwFlags %x, thread id %u", pCardData, dwFlags, GetCurrentThreadId());
  CMD_NONNULL_PARAM(pCardData);
  cmd_print_stack();

  if (dwFlags & CARD_SECURE_KEY_INJECTION_NO_CARD_MODE) {
    CMD_RETURN(SCARD_E_INVALID_PARAMETER, "CARD_SECURE_KEY_INJECTION_NO_CARD_MODE");
  }

  if (pCardData->dwVersion < CARD_DATA_VERSION_FOUR) {
    CMD_RETURN(ERROR_REVISION_MISMATCH, "dwVersion too old");
  }
  CMD_DEBUG("dwVersion %d", pCardData->dwVersion);

  CMD_ENSURE_VALID_HANDLE(pCardData->hSCardCtx, SCARD_E_INVALID_HANDLE);
  CMD_ENSURE_VALID_HANDLE(pCardData->hScard, SCARD_E_INVALID_HANDLE);
  CMD_DEBUG("hScardCtx %p, hScard %p", pCardData->hSCardCtx, pCardData->hScard);

  CMD_NONNULL_PARAM(pCardData->pfnCspAlloc);
  CMD_NONNULL_PARAM(pCardData->pfnCspReAlloc);
  CMD_NONNULL_PARAM(pCardData->pfnCspFree);

  if (!pCardData->pbAtr || pCardData->cbAtr == 0) {
    CMD_RETURN(ERROR_INVALID_PARAMETER, "No pbAtr or cbAtr");
  }

  CMD_ENSURE_NONNULL(pCardData->pwszCardName, SCARD_E_INVALID_PARAMETER);
  CMD_DEBUG("pwszCardName %S", pCardData->pwszCardName);

  // TODO: check pbAtr content

  // CardAcquireContext and CardDeleteContext mutate the same process-wide
  // managed binding. Keep the exclusive lock until the new CARD_DATA owns a
  // fully initialized CMD_CONTEXT, so delete cannot finalize it mid-acquire.
  AcquireSRWLockExclusive(&g_cmd_context_lock);
  PSRWLOCK contextLock __attribute__((cleanup(release_exclusive_context_lock))) = &g_cmd_context_lock;
  if (pCardData->pvVendorSpecific != NULL)
    CMD_RETURN(SCARD_E_INVALID_PARAMETER, "CARD_DATA context is already acquired");

  // Validate the process-wide managed binding before publishing callbacks.
  // A failed second acquisition must not replace the allocator used by the
  // already-active context.
  CNK_MANAGED_MODE_INIT_ARGS managedArgs = {.malloc_func = (CNK_MALLOC_FUNC)pCardData->pfnCspAlloc,
                                            .free_func = (CNK_FREE_FUNC)pCardData->pfnCspFree,
                                            .hSCardCtx = pCardData->hSCardCtx,
                                            .hScard = pCardData->hScard};
  CK_RV managedRv = C_CNK_EnableManagedMode(&managedArgs);
  if (managedRv != CKR_OK && managedRv != CKR_CRYPTOKI_ALREADY_INITIALIZED)
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot bind managed card context");

  // Import callbacks only after managed binding validation succeeds.
  g_pfnCspAlloc = pCardData->pfnCspAlloc;
  g_pfnCspFree = pCardData->pfnCspFree;
  g_pfnCspPadData = pCardData->pfnCspPadData;

  // Set function pointers in pCardData
  pCardData->pfnCardDeleteContext = CardDeleteContext;             // Yes
  pCardData->pfnCardQueryCapabilities = CardQueryCapabilities;     // Yes
  pCardData->pfnCardDeleteContainer = NULL;                        // No
  pCardData->pfnCardCreateContainer = CardCreateContainer;         // Yes
  pCardData->pfnCardGetContainerInfo = CardGetContainerInfo;       // Yes
  pCardData->pfnCardAuthenticatePin = CardAuthenticatePin;         // Yes
  pCardData->pfnCardGetChallenge = NULL;                           // No (opt)
  pCardData->pfnCardAuthenticateChallenge = NULL;                  // No (opt)
  pCardData->pfnCardUnblockPin = CardUnblockPin;                   // Yes (opt)
  pCardData->pfnCardChangeAuthenticator = CardChangeAuthenticator; // Yes
  pCardData->pfnCardDeauthenticate = NULL;                         // No (opt, NULL means Base CSP may reset the card)
  pCardData->pfnCardCreateDirectory = NULL;                        // No
  pCardData->pfnCardDeleteDirectory = NULL;                        // No
  pCardData->pfnCardCreateFile = CardCreateFile;                   // Yes
  pCardData->pfnCardReadFile = CardReadFile;                       // Yes
  pCardData->pfnCardWriteFile = CardWriteFile;                     // Yes
  pCardData->pfnCardDeleteFile = NULL;                             // No
  pCardData->pfnCardEnumFiles = CardEnumFiles;                     // Yes
  pCardData->pfnCardGetFileInfo = CardGetFileInfo;                 // Yes
  pCardData->pfnCardQueryFreeSpace = CardQueryFreeSpace;           // Yes
  pCardData->pfnCardQueryKeySizes = CardQueryKeySizes;             // Yes

  pCardData->pfnCardSignData = CardSignData;                         // Yes
  pCardData->pfnCardRSADecrypt = CardRSADecrypt;                     // Yes (opt)
  pCardData->pfnCardConstructDHAgreement = CardConstructDHAgreement; // Yes (opt)

  // New functions in version five.
  pCardData->pfnCardDeriveKey = CardDeriveKey;                   // Yes (opt)
  pCardData->pfnCardDestroyDHAgreement = CardDestroyDHAgreement; // Yes (opt)
  // pCardData->pfnCspGetDHAgreement;

  // version 6 additions below here
  pCardData->pfnCardGetChallengeEx = NULL;                             // No (opt)
  pCardData->pfnCardAuthenticateEx = CardAuthenticateEx;               // Yes
  pCardData->pfnCardChangeAuthenticatorEx = CardChangeAuthenticatorEx; // Yes (opt)
  pCardData->pfnCardDeauthenticateEx = CardDeauthenticateEx;           // Yes
  pCardData->pfnCardGetContainerProperty = CardGetContainerProperty;   // Yes
  pCardData->pfnCardSetContainerProperty = NULL;                       // No
  pCardData->pfnCardGetProperty = CardGetProperty;                     // Yes
  pCardData->pfnCardSetProperty = CardSetProperty;                     // Yes

  // version 7 additions below here
  // pCardData->pfnCspUnpadData;
  pCardData->pfnMDImportSessionKey = NULL;                     // No (opt)
  pCardData->pfnMDEncryptData = NULL;                          // No (opt)
  pCardData->pfnCardImportSessionKey = NULL;                   // No (opt)
  pCardData->pfnCardGetSharedKeyHandle = NULL;                 // No (opt)
  pCardData->pfnCardGetAlgorithmProperty = NULL;               // No (opt)
  pCardData->pfnCardGetKeyProperty = NULL;                     // No (opt)
  pCardData->pfnCardSetKeyProperty = NULL;                     // No (opt)
  pCardData->pfnCardDestroyKey = NULL;                         // No (opt)
  pCardData->pfnCardProcessEncryptedData = NULL;               // No (opt)
  pCardData->pfnCardCreateContainerEx = CardCreateContainerEx; // Yes (opt)

  // fill in generated stubs
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wcompare-distinct-pointer-types"

  // clang-format off
#define CMD_SET_CARD_DATA_PFN(NAME) do { \
  if (pCardData->pfn## NAME != NULL) { \
    CMD_ERROR("pCardData->pfn%s (set to %p) overridden by generated stub\n", #NAME, pCardData->pfn## NAME); \
  } \
  pCardData->pfn## NAME = (void *) CMD_NO_IMPL_FUNC_NAME(NAME); \
} while (0);
INVOKE_X_ON_NO_IMPL_FUNCS(CMD_SET_CARD_DATA_PFN);
#undef CMD_SET_CARD_DATA_PFN
#undef CMD_NO_IMPL_FUNC_NAME
  // clang-format on

  // check whether pCardData is fully filled
  uintptr_t *begin = (uintptr_t *)&pCardData->pfnCardDeleteContext;
  uintptr_t *end = (uintptr_t *)&pCardData->pfnCardCreateContainerEx;
  for (uintptr_t *p = begin; p <= end; p++) {
    if (*p == 0 &&
        !(p == (uintptr_t *)&pCardData->pvUnused3 || p == (uintptr_t *)&pCardData->pvUnused4 ||
          p == (uintptr_t *)&pCardData->pfnCardDeauthenticate || p == (uintptr_t *)&pCardData->pfnCspGetDHAgreement ||
          p == (uintptr_t *)&pCardData->pfnCspUnpadData)) {
      CMD_ERROR("pCardData has NULL entry point at offset %lld to pfnCardDeleteContext, check CardAcquireContext!\n",
                p - begin);
    }
  }

#pragma clang diagnostic pop

  // Allocate the retryable context before initialization. If a later cleanup
  // callback fails, pvVendorSpecific remains available for CardDeleteContext.
  CMD_CONTEXT_PTR context = g_pfnCspAlloc(sizeof(CMD_CONTEXT));
  if (context == NULL) {
    CK_RV resetRv = C_CNK_ResetManagedMode();
    if (resetRv != CKR_OK)
      CMD_WARN("Managed binding rollback after allocation failure failed: 0x%lx", resetRv);
    CMD_RETURN(SCARD_E_NO_MEMORY, "cannot allocate context");
  }
  memset(context, 0, sizeof(*context));
  pCardData->pvVendorSpecific = context;

  // initialize canokey-pkcs11
  CK_RV ret = C_Initialize(NULL);
  if (ret != CKR_OK && ret != CKR_CRYPTOKI_ALREADY_INITIALIZED) {
    CK_RV resetRv = C_CNK_ResetManagedMode();
    if (resetRv != CKR_OK)
      CMD_WARN("Managed binding rollback after C_Initialize failure failed: 0x%lx", resetRv);
    if (resetRv == CKR_OK) {
      pCardData->pvVendorSpecific = NULL;
      g_pfnCspFree(context);
    }
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot initialize canokey-pkcs11");
  }

  ret = C_OpenSession(0, CKF_SERIAL_SESSION | CKF_RW_SESSION, NULL, NULL, &context->session);
  if (ret != CKR_OK) {
    CK_RV cleanupRv = cleanup_failed_acquire(CK_INVALID_HANDLE, FALSE);
    if (cleanupRv == CKR_OK) {
      pCardData->pvVendorSpecific = NULL;
      g_pfnCspFree(context);
    } else {
      CMD_WARN("Acquire cleanup was incomplete: 0x%lx", cleanupRv);
    }
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot open session");
  }

  ret = read_canokey(context->session, &context->canokey);
  if (ret != CKR_OK) {
    CK_RV cleanupRv = cleanup_failed_acquire(context->session, TRUE);
    if (cleanupRv == CKR_OK) {
      pCardData->pvVendorSpecific = NULL;
      g_pfnCspFree(context);
    } else {
      CMD_WARN("Acquire cleanup was incomplete: 0x%lx", cleanupRv);
    }
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot read canokey");
  }

  DWORD dwRet = GenerateCardIdentifier(context);
  if (dwRet != SCARD_S_SUCCESS) {
    CK_RV cleanupRv = cleanup_failed_acquire(context->session, TRUE);
    if (cleanupRv == CKR_OK) {
      pCardData->pvVendorSpecific = NULL;
      g_pfnCspFree(context);
    } else {
      CMD_WARN("Acquire cleanup was incomplete: 0x%lx", cleanupRv);
    }
    CMD_RETURN(dwRet, "cannot generate card identifier");
  }

  CMD_RET_OK;
}

DWORD CardDeleteContext(__inout PCARD_DATA pCardData) {
  CMD_LOG_FUNC("pCardData %p", pCardData);
  CMD_NONNULL_PARAM(pCardData);
  AcquireSRWLockExclusive(&g_cmd_context_lock);
  PSRWLOCK contextLock __attribute__((cleanup(release_exclusive_context_lock))) = &g_cmd_context_lock;
  if (pCardData->pvVendorSpecific) {
    CMD_CONTEXT_PTR context = (CMD_CONTEXT_PTR)pCardData->pvVendorSpecific;
    CK_RV rv = C_CloseSession(context->session);
    if (rv != CKR_OK && rv != CKR_SESSION_HANDLE_INVALID && rv != CKR_CRYPTOKI_NOT_INITIALIZED) {
      CMD_WARN("C_CloseSession failed: 0x%lx", rv);
      CMD_RETURN(SCARD_F_INTERNAL_ERROR, "C_CloseSession failed");
    }
    rv = C_Finalize(NULL);
    if (rv != CKR_OK && rv != CKR_CRYPTOKI_NOT_INITIALIZED) {
      CMD_WARN("C_Finalize failed: 0x%lx", rv);
      CMD_RETURN(SCARD_F_INTERNAL_ERROR, "C_Finalize failed");
    }
    if (rv == CKR_CRYPTOKI_NOT_INITIALIZED)
      C_CNK_ResetManagedMode();
    SecureZeroMemory(context->dhAgreements, sizeof(context->dhAgreements));
    pCardData->pfnCspFree(context);
    pCardData->pvVendorSpecific = NULL;
  }
  CMD_RET_OK;
}
