#include <Windows.h>
#include <string.h>

#include "cardmod.h"
#include "logging.h"
#include "minidriver.h"
#include "pkcs11.h"

// clang-format off
// This is the list of functions required by the spec
// that we **do not want** to support.
// Please make sure any function is either listed here
// or has a concrete definition. Otherwise, this mini driver
// would be silently ignored by CSP.
#define INVOKE_X_ON_NO_IMPL_FUNCS(X) \
X(CardDeleteContainer) \
X(CardCreateContainer) \
X(CardGetChallenge) \
X(CardAuthenticateChallenge) \
X(CardUnblockPin) \
X(CardChangeAuthenticator) \
X(CardDeauthenticate) \
X(CardCreateDirectory) \
X(CardDeleteDirectory) \
X(CardCreateFile) \
X(CardWriteFile) \
X(CardDeleteFile) \
X(CardSetContainerProperty) \
X(CardGetChallengeEx) \
X(CardChangeAuthenticatorEx) \
X(MDImportSessionKey) \
X(MDEncryptData) \
X(CardImportSessionKey) \
X(CardGetSharedKeyHandle) \
X(CardGetAlgorithmProperty) \
X(CardGetKeyProperty) \
X(CardSetKeyProperty) \
X(CardDestroyKey) \
X(CardProcessEncryptedData) \
X(CardCreateContainerEx)

#define CMD_NO_IMPL_FUNC_NAME(NAME) __cmd_noimpl__ ## NAME
#define CMD_GEN_NO_IMPL_FUNC(NAME) DWORD WINAPI CMD_NO_IMPL_FUNC_NAME(NAME)(__inout PCARD_DATA pCardData, ...) { \
CMD_ERROR(#NAME " is not meant to be supported but called with pCardData %p", pCardData); \
CMD_RETURN(SCARD_E_UNSUPPORTED_FEATURE, "not meant to be supported (generated by macro)"); \
}
INVOKE_X_ON_NO_IMPL_FUNCS(CMD_GEN_NO_IMPL_FUNC);
#undef CMD_GEN_NO_IMPL_FUNC
// clang-format on

// Global function pointers for data caching mechanisms
PFN_CSP_CACHE_ADD_FILE g_pfnCspCacheAddFile = NULL;
PFN_CSP_CACHE_LOOKUP_FILE g_pfnCspCacheLookupFile = NULL;
PFN_CSP_CACHE_DELETE_FILE g_pfnCspCacheDeleteFile = NULL;

// Global function pointers for memory management
PFN_CSP_ALLOC g_pfnCspAlloc = NULL;
PFN_CSP_REALLOC g_pfnCspReAlloc = NULL;
PFN_CSP_FREE g_pfnCspFree = NULL;

// Global function pointer for padding
PFN_CSP_PAD_DATA g_pfnCspPadData = NULL;

// Global function pointer for padding removal
PFN_CSP_UNPAD_DATA g_pfnCspUnpadData = NULL;

/*
 * Function: CardAcquireContext
 *
 * Purpose: Initialize the CARD_DATA structure which will be used by
 *          the CSP to interact with a specific card.
 */
DWORD WINAPI CardAcquireContext(__inout PCARD_DATA pCardData, __in DWORD dwFlags) {
  CMD_LOG_FUNC("pCardData %p, dwFlags %x, thread id %u", pCardData, dwFlags, GetCurrentThreadId());
  CMD_NONNULL_PARAM(pCardData);
  cmd_print_stack();

  if (dwFlags & CARD_SECURE_KEY_INJECTION_NO_CARD_MODE) {
    CMD_RETURN(SCARD_E_INVALID_PARAMETER, "CARD_SECURE_KEY_INJECTION_NO_CARD_MODE");
  }

  if (pCardData->dwVersion < CARD_DATA_VERSION_FOUR) {
    CMD_RETURN(ERROR_REVISION_MISMATCH, "dwVersion too old");
  }
  CMD_DEBUG("dwVersion %d", pCardData->dwVersion);

  CMD_ENSURE_VALID_HANDLE(pCardData->hSCardCtx, SCARD_E_INVALID_HANDLE);
  CMD_ENSURE_VALID_HANDLE(pCardData->hScard, SCARD_E_INVALID_HANDLE);
  CMD_DEBUG("hScardCtx %p, hScard %p", pCardData->hSCardCtx, pCardData->hScard);

  CMD_NONNULL_PARAM(pCardData->pfnCspAlloc);
  CMD_NONNULL_PARAM(pCardData->pfnCspReAlloc);
  CMD_NONNULL_PARAM(pCardData->pfnCspFree);

  if (!pCardData->pbAtr || pCardData->cbAtr == 0) {
    CMD_RETURN(ERROR_INVALID_PARAMETER, "No pbAtr or cbAtr");
  }

  CMD_ENSURE_NONNULL(pCardData->pwszCardName, SCARD_E_INVALID_PARAMETER);
  CMD_DEBUG("pwszCardName %S", pCardData->pwszCardName);

  // TODO: check pbAtr content

  // Import the data caching functions
  g_pfnCspCacheAddFile = pCardData->pfnCspCacheAddFile;
  g_pfnCspCacheLookupFile = pCardData->pfnCspCacheLookupFile;
  g_pfnCspCacheDeleteFile = pCardData->pfnCspCacheDeleteFile;

  // Import the memory management functions
  g_pfnCspAlloc = pCardData->pfnCspAlloc;
  g_pfnCspReAlloc = pCardData->pfnCspReAlloc;
  g_pfnCspFree = pCardData->pfnCspFree;

  // Import the padding function
  g_pfnCspPadData = pCardData->pfnCspPadData;

  // Import the padding removal function
  if (pCardData->dwVersion >= CARD_DATA_VERSION_SEVEN) {
    g_pfnCspUnpadData = pCardData->pfnCspUnpadData;
  }

  // Set function pointers in pCardData
  pCardData->pfnCardDeleteContext = CardDeleteContext;         // Yes
  pCardData->pfnCardQueryCapabilities = CardQueryCapabilities; // Yes
  pCardData->pfnCardDeleteContainer = NULL;                    // No
  pCardData->pfnCardCreateContainer = NULL;                    // No
  pCardData->pfnCardGetContainerInfo = CardGetContainerInfo;   // Yes
  pCardData->pfnCardAuthenticatePin = CardAuthenticatePin;     // Yes
  pCardData->pfnCardGetChallenge = NULL;                       // No (opt)
  pCardData->pfnCardAuthenticateChallenge = NULL;              // No (opt)
  pCardData->pfnCardUnblockPin = NULL;                         // No (opt)
  pCardData->pfnCardChangeAuthenticator = NULL;                // No (opt)
  pCardData->pfnCardDeauthenticate = NULL;                     // Yes (opt)
  pCardData->pfnCardCreateDirectory = NULL;                    // No
  pCardData->pfnCardDeleteDirectory = NULL;                    // No
  pCardData->pfnCardCreateFile = NULL;                         // No
  pCardData->pfnCardReadFile = CardReadFile;                   // Yes
  pCardData->pfnCardWriteFile = NULL;                          // No
  pCardData->pfnCardDeleteFile = NULL;                         // No
  pCardData->pfnCardEnumFiles = CardEnumFiles;                 // Yes
  pCardData->pfnCardGetFileInfo = CardGetFileInfo;             // Yes
  pCardData->pfnCardQueryFreeSpace = CardQueryFreeSpace;       // Yes
  pCardData->pfnCardQueryKeySizes = CardQueryKeySizes;         // Yes

  pCardData->pfnCardSignData = CardSignData;                         // Yes
  pCardData->pfnCardRSADecrypt = CardRSADecrypt;                     // Yes (opt)
  pCardData->pfnCardConstructDHAgreement = CardConstructDHAgreement; // Yes (opt)

  // New functions in version five.
  pCardData->pfnCardDeriveKey = CardDeriveKey;                   // Yes (opt)
  pCardData->pfnCardDestroyDHAgreement = CardDestroyDHAgreement; // Yes (opt)
  // pCardData->pfnCspGetDHAgreement;

  // version 6 additions below here
  pCardData->pfnCardGetChallengeEx = NULL;                           // No (opt)
  pCardData->pfnCardAuthenticateEx = CardAuthenticateEx;             // Yes
  pCardData->pfnCardChangeAuthenticatorEx = NULL;                    // No (opt)
  pCardData->pfnCardDeauthenticateEx = CardDeauthenticateEx;         // Yes
  pCardData->pfnCardGetContainerProperty = CardGetContainerProperty; // Yes
  pCardData->pfnCardSetContainerProperty = NULL;                     // No
  pCardData->pfnCardGetProperty = CardGetProperty;                   // Yes
  pCardData->pfnCardSetProperty = CardSetProperty;                   // Yes

  // version 7 additions below here
  // pCardData->pfnCspUnpadData;
  pCardData->pfnMDImportSessionKey = NULL;       // No (opt)
  pCardData->pfnMDEncryptData = NULL;            // No (opt)
  pCardData->pfnCardImportSessionKey = NULL;     // No (opt)
  pCardData->pfnCardGetSharedKeyHandle = NULL;   // No (opt)
  pCardData->pfnCardGetAlgorithmProperty = NULL; // No (opt)
  pCardData->pfnCardGetKeyProperty = NULL;       // No (opt)
  pCardData->pfnCardSetKeyProperty = NULL;       // No (opt)
  pCardData->pfnCardDestroyKey = NULL;           // No (opt)
  pCardData->pfnCardProcessEncryptedData = NULL; // No (opt)
  pCardData->pfnCardCreateContainerEx = NULL;    // No (opt)

  // fill in generated stubs
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wcompare-distinct-pointer-types"

  // clang-format off
#define CMD_SET_CARD_DATA_PFN(NAME) do { \
  if (pCardData->pfn## NAME != NULL) { \
    CMD_ERROR("pCardData->pfn%s (set to %p) overridden by generated stub\n", #NAME, pCardData->pfn## NAME); \
  } \
  pCardData->pfn## NAME = (void *) CMD_NO_IMPL_FUNC_NAME(NAME); \
} while (0);
INVOKE_X_ON_NO_IMPL_FUNCS(CMD_SET_CARD_DATA_PFN);
#undef CMD_SET_CARD_DATA_PFN
#undef CMD_NO_IMPL_FUNC_NAME
  // clang-format on

  // check whether pCardData is fully filled
  uintptr_t *begin = (uintptr_t *)&pCardData->pfnCardDeleteContext;
  uintptr_t *end = (uintptr_t *)&pCardData->pfnCardCreateContainerEx;
  for (uintptr_t *p = begin; p <= end; p++) {
    if (*p == 0 &&
        !(p == (uintptr_t *)&pCardData->pvUnused3 || p == (uintptr_t *)&pCardData->pvUnused4 ||
          p == (uintptr_t *)&pCardData->pfnCspGetDHAgreement || p == (uintptr_t *)&pCardData->pfnCspUnpadData)) {
      CMD_ERROR("pCardData has NULL entry point at offset %lld to pfnCardDeleteContext, check CardAcquireContext!\n",
                p - begin);
    }
  }

#pragma clang diagnostic pop

  // initialize canokey-pkcs11
  INJECT_HANDLES();

  CK_RV ret = C_Initialize(NULL);
  if (ret != CKR_OK && ret != CKR_CRYPTOKI_ALREADY_INITIALIZED) {
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot initialize canokey-pkcs11");
  }
  CMD_CONTEXT_PTR context = g_pfnCspAlloc(sizeof(CMD_CONTEXT));
  if (context == NULL) {
    C_Finalize(NULL);
    CMD_RETURN(SCARD_E_NO_MEMORY, "cannot allocate context");
  }
  memset(context, 0, sizeof(*context));

  ret = C_OpenSession(0, CKF_SERIAL_SESSION | CKF_RW_SESSION, NULL, NULL, &context->session);
  if (ret != CKR_OK) {
    g_pfnCspFree(context);
    C_Finalize(NULL);
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot open session");
  }

  ret = read_canokey(context->session, &context->canokey);
  if (ret != CKR_OK) {
    C_CloseSession(context->session);
    g_pfnCspFree(context);
    C_Finalize(NULL);
    CMD_RETURN(SCARD_F_INTERNAL_ERROR, "cannot read canokey");
  }

  pCardData->pvVendorSpecific = context;
  CMD_RET_OK;
}

DWORD CardDeleteContext(__inout PCARD_DATA pCardData) {
  CMD_LOG_FUNC("pCardData %p", pCardData);
  CMD_NONNULL_PARAM(pCardData);
  if (pCardData->pvVendorSpecific) {
    CMD_CONTEXT_PTR context = (CMD_CONTEXT_PTR)pCardData->pvVendorSpecific;
    CK_RV rv = C_CloseSession(context->session);
    if (rv != CKR_OK && rv != CKR_SESSION_HANDLE_INVALID && rv != CKR_CRYPTOKI_NOT_INITIALIZED) {
      CMD_WARN("C_CloseSession failed: 0x%lx", rv);
    }
    SecureZeroMemory(context->dhAgreements, sizeof(context->dhAgreements));
    pCardData->pfnCspFree(context);
    pCardData->pvVendorSpecific = NULL;

    rv = C_Finalize(NULL);
    if (rv != CKR_OK && rv != CKR_CRYPTOKI_NOT_INITIALIZED) {
      CMD_WARN("C_Finalize failed: 0x%lx", rv);
    }
  }
  CMD_RET_OK;
}
